version: '3.9'

services:
  backend:
    build: ./backend
    container_name: catch-backend
    command: npm run start
    ports:
      - "3001:3001"
    volumes:
      - "./backend:/app"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:wael01234@mongo:27017/catch-db?authSource=admin
    networks:
      - catchApp-networks

  frontend:
    build: ./frontend
    container_name: catch-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/src"
    environment:
      - REACT_APP_API_URL=http://localhost:3001  # Use the backend service name
    networks:
      - catchApp-networks

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wael01234
    volumes:
      - catch-db-data:/data/db
    container_name: catch-db
    ports:
      - "27017:27017"
    networks:
      - catchApp-networks

networks:
  catchApp-networks:
    driver: bridge

volumes:
  catch-db-data: {}
